# Generated by Django 5.0.7 on 2024-08-12 09:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movieapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adminlogin",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="adminlogin",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="adminlogin",
            name="user_permissions",
        ),
    ]
