# Generated by Django 5.0.7 on 2024-08-15 20:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movieapp", "0002_remove_adminlogin_groups_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movielist",
            old_name="vedio",
            new_name="video",
        ),
    ]
