# Generated by Django 5.0.7 on 2024-08-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movieapp", "0003_rename_vedio_movielist_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movielist",
            name="video",
            field=models.FileField(upload_to="videos/"),
        ),
    ]
